#-----------------------------------------------------
#-- Docker compose base defenition file for MYSQL DB--
#-----------------------------------------------------
# Create a MYSQL DB server container

version: '3.6'
services:
  db-service:
    build:
      context: ${DB_CONTEXT}
      dockerfile: Dockerfile
      args:
        DB_BASE_IMAGE: ${DB_BASE_IMAGE}
    image: ${DB_IMAGE}
    container_name: mysql-learning
    shm_size: '1gb'
    ports:
      - "5500:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}